/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * <p>
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.queue.implementation;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.microsoft.azure.storage.queue.models.ListQueuesIncludeType;

import java.util.ArrayList;
import java.util.List;

/**
 * A wrapper around List&lt;ListQueuesIncludeType&gt; which provides top-level metadata for serialization.
 */
@JacksonXmlRootElement(localName = "ListQueuesIncludeType")
public final class ListQueuesIncludeTypeWrapper {
    @JacksonXmlProperty(localName = "ListQueuesIncludeType")
    private final List<ListQueuesIncludeType> listQueuesIncludeType;

    /**
     * Creates an instance of ListQueuesIncludeTypeWrapper.
     *
     * @param listQueuesIncludeType
     *         the list.
     */
    @JsonCreator
    public ListQueuesIncludeTypeWrapper(@JsonProperty("ListQueuesIncludeType") List<ListQueuesIncludeType> listQueuesIncludeType) {
        this.listQueuesIncludeType = listQueuesIncludeType;
    }

    /**
     * Get the List&lt;ListQueuesIncludeType&gt; contained in this wrapper.
     *
     * @return the List&lt;ListQueuesIncludeType&gt;.
     */
    public List<ListQueuesIncludeType> items() {
        return listQueuesIncludeType;
    }
}
